{
 "title": "Prometheus Simple Self-Monitoring",
 "refresh": "10s",
 "panels": [
  {
   "title": "UP metric (targets state)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Prometheus memory usage (RSS)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "RSS" }
   ]
  },
  {
   "title": "Prometheus CPU seconds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "CPU"
    }
   ]
  }
 ]
}